import React, { useState, useRef, useCallback, useMemo, useEffect } from 'react';
import { View, Text, Pressable, StyleSheet, SafeAreaView, useWindowDimensions, Modal, BackHandler } from 'react-native';
import { Audio } from 'expo-av';
import { useFocusEffect } from '@react-navigation/native';
import { colors } from '../theme/colors';
import { useGame } from '../context/GameContext';
import { shuffle } from '../utils/shuffle';
import { generateLayout } from '../utils/layout';
import { getNumberCount, getButtonSize, getTimeLimitMs } from '../utils/difficulty';
import { saveRunResult } from '../utils/storage';
import NumberButton from '../components/NumberButton';
import Timer from '../components/Timer';
const HEADER_HEIGHT=84,TICK_MS=100;
const WRONG_SOUND='https://actions.google.com/sounds/v1/cartoon/wood_plank_flicks.ogg';
export default function GameScreen({navigation}){const{width}=useWindowDimensions();const{level,score,lives,registerCorrectTap,registerWrongTap,completeLevel}=useGame();const maxNumber=getNumberCount(level);const buttonSize=getButtonSize(level);const timeLimitMs=getTimeLimitMs(level);const[playArea,setPlayArea]=useState({w:0,h:0});const[layoutSeed,setLayoutSeed]=useState(0);const[nextExpected,setNextExpected]=useState(1);const[statuses,setStatuses]=useState({});const[elapsedMs,setElapsedMs]=useState(0);const[isPaused,setIsPaused]=useState(false);const intervalRef=useRef(null),levelStartRef=useRef(Date.now()),endedRef=useRef(false),wrongSoundRef=useRef(null);
useEffect(()=>{let mounted=true;(async()=>{try{await Audio.setAudioModeAsync({playsInSilentMode:true});const{sound}=await Audio.Sound.createAsync({uri:WRONG_SOUND},{shouldPlay:false});if(mounted)wrongSoundRef.current=sound;else await sound.unloadAsync()}catch(e){}})();return()=>{mounted=false;if(wrongSoundRef.current){wrongSoundRef.current.unloadAsync();wrongSoundRef.current=null}}},[]);
const playWrongSound=useCallback(async()=>{try{const sound=wrongSoundRef.current;if(!sound)return;await sound.setPositionAsync(0);await sound.playAsync()}catch(e){}},[]);
const numbers=useMemo(()=>Array.from({length:maxNumber},(_,i)=>i+1),[maxNumber]);const shuffledOrder=useMemo(()=>shuffle(numbers),[numbers,layoutSeed]);const positions=useMemo(()=>playArea.w&&playArea.h?generateLayout(maxNumber,buttonSize,playArea.w,playArea.h):[],[maxNumber,buttonSize,playArea,layoutSeed]);const valueToPosition=useMemo(()=>{const map={};shuffledOrder.forEach((value,i)=>{map[value]=positions[i]});return map},[shuffledOrder,positions]);
const decoyHighlight=useMemo(()=>{const candidates=numbers.filter(n=>n!==nextExpected);if(!candidates.length)return null;const seed=Math.abs((nextExpected*31)+(level*17)+layoutSeed*13);return candidates[seed%candidates.length]},[numbers,nextExpected,level,layoutSeed]);
const resetLevelState=useCallback(()=>{endedRef.current=false;setNextExpected(1);setStatuses({});setElapsedMs(0);levelStartRef.current=Date.now();setLayoutSeed(s=>s+1)},[]);
useFocusEffect(useCallback(()=>{setIsPaused(false);const onBackPress=()=>{if(endedRef.current)return true;setIsPaused(true);return true};const subscription=BackHandler.addEventListener('hardwareBackPress',onBackPress);return()=>subscription.remove()},[]));
React.useEffect(()=>{if(isPaused||endedRef.current)return;intervalRef.current=setInterval(()=>setElapsedMs(p=>p+TICK_MS),TICK_MS);return()=>clearInterval(intervalRef.current)},[isPaused,layoutSeed]);const remainingMs=timeLimitMs!=null?Math.max(0,timeLimitMs-elapsedMs):null;const endLevelSuccess=useCallback(()=>{if(endedRef.current)return;endedRef.current=true;clearInterval(intervalRef.current);completeLevel(remainingMs!=null?remainingMs/1000:null);navigation.replace('LevelComplete',{timeMs:elapsedMs,maxNumber})},[completeLevel,navigation,elapsedMs,maxNumber,remainingMs]);const endGame=useCallback(async(reason)=>{if(endedRef.current)return;endedRef.current=true;clearInterval(intervalRef.current);const{isNewBestScore,isNewBestLevel}=await saveRunResult({score,level,bestLevelTimeMs:null});navigation.replace('GameOver',{finalScore:score,finalLevel:level,reason,isNewBestScore,isNewBestLevel})},[navigation,score,level]);React.useEffect(()=>{if(remainingMs===0&&!endedRef.current)endGame('time')},[remainingMs,endGame]);const handleTap=useCallback(value=>{if(endedRef.current||isPaused)return;if(value===nextExpected){setStatuses(p=>({...p,[value]:'correct'}));registerCorrectTap();if(value===maxNumber)endLevelSuccess();else setNextExpected(n=>n+1)}else{setStatuses(p=>({...p,[value]:'wrong'}));registerWrongTap();playWrongSound();setTimeout(()=>setStatuses(p=>{if(p[value]!=='wrong')return p;const n={...p};delete n[value];return n}),300);if(lives-1<=0)endGame('lives')}},[nextExpected,maxNumber,isPaused,registerCorrectTap,registerWrongTap,playWrongSound,endLevelSuccess,endGame,lives]);
return <SafeAreaView style={styles.flex}><View style={styles.header}><HeaderItem label="LEVEL" value={level}/><HeaderItem label="SCORE" value={score}/><View style={styles.headerItem}><Text style={styles.headerLabel}>TIME</Text><Timer elapsedMs={elapsedMs} remainingMs={remainingMs}/></View><HeaderItem label="LIVES" value={'♥'.repeat(Math.max(lives,0))}/><Pressable style={styles.pauseButton} onPress={()=>setIsPaused(true)} hitSlop={10}><Text style={styles.pauseIcon}>⏸</Text></Pressable></View><View style={styles.playArea} onLayout={e=>{const{width:w,height:h}=e.nativeEvent.layout;setPlayArea({w,h})}}>{numbers.map(value=>{const pos=valueToPosition[value];if(!pos)return null;const isDecoy=value===decoyHighlight&&statuses[value]==null&&value!==nextExpected;return <NumberButton key={value} value={value} x={pos.x} y={pos.y} size={buttonSize} status={statuses[value]||'idle'} decoy={isDecoy} onPress={handleTap} disabled={value<nextExpected}/>})}</View><Modal visible={isPaused} transparent animationType="fade"><View style={styles.overlay}><View style={styles.pauseCard}><Text style={styles.pauseTitle}>Paused</Text><Pressable style={styles.modalButton} onPress={()=>setIsPaused(false)}><Text style={styles.modalButtonText}>Resume</Text></Pressable><Pressable style={[styles.modalButton,styles.modalButtonSecondary]} onPress={()=>{setIsPaused(false);resetLevelState()}}><Text style={styles.modalButtonText}>Restart Level</Text></Pressable><Pressable style={[styles.modalButton,styles.modalButtonSecondary]} onPress={()=>{setIsPaused(false);navigation.replace('Home')}}><Text style={styles.modalButtonText}>Quit to Home</Text></Pressable></View></View></Modal></SafeAreaView>}
function HeaderItem({label,value}){return <View style={styles.headerItem}><Text style={styles.headerLabel}>{label}</Text><Text style={styles.headerValue}>{value}</Text></View>}
const styles=StyleSheet.create({flex:{flex:1,backgroundColor:colors.background},header:{height:HEADER_HEIGHT,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16},headerItem:{alignItems:'center'},headerLabel:{color:colors.textSecondary,fontSize:11,fontWeight:'600'},headerValue:{color:colors.textPrimary,fontSize:18,fontWeight:'700'},pauseButton:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},pauseIcon:{color:colors.textPrimary,fontSize:16},playArea:{flex:1,position:'relative',marginHorizontal:8},overlay:{flex:1,backgroundColor:colors.overlay,alignItems:'center',justifyContent:'center'},pauseCard:{backgroundColor:colors.surface,borderRadius:20,padding:24,width:280},pauseTitle:{color:colors.textPrimary,fontSize:22,fontWeight:'700',textAlign:'center',marginBottom:20},modalButton:{backgroundColor:colors.primary,paddingVertical:14,borderRadius:14,alignItems:'center',marginBottom:10},modalButtonSecondary:{backgroundColor:colors.buttonIdle},modalButtonText:{color:colors.textPrimary,fontSize:16,fontWeight:'700'}});