import React, { useEffect, useState } from 'react';
import { View, Text, Pressable, StyleSheet, SafeAreaView } from 'react-native';
import { colors } from '../theme/colors';
import { useGame } from '../context/GameContext';
import { getBestScore } from '../utils/storage';
import { useRewardedAd } from '../utils/useRewardedAd';
const REASON_TEXT={lives:'Out of lives!',time:"Time's up!"};
export default function GameOverScreen({navigation,route}){const{finalScore,finalLevel,reason,isNewBestScore}=route.params;const{resetRun,continueAfterAd}=useGame();const[bestScore,setBestScore]=useState(finalScore);const{showAd,isLoaded:rewardedLoaded}=useRewardedAd();const[continueUsed,setContinueUsed]=useState(false);useEffect(()=>{getBestScore().then(setBestScore)},[]);const handlePlayAgain=()=>{resetRun();navigation.replace('Game')};const handleContinue=()=>{const started=showAd(()=>{continueAfterAd();navigation.replace('Game')});if(started)setContinueUsed(true)};return <SafeAreaView style={styles.flex}><View style={styles.content}><Text style={styles.reason}>{REASON_TEXT[reason]||'Game Over'}</Text><Text style={styles.title}>Game Over</Text>{isNewBestScore&&<Text style={styles.newRecord}>🏆 New Best Score!</Text>}<View style={styles.statsBlock}><StatRow label="Final Score" value={String(finalScore)} highlight={isNewBestScore}/><StatRow label="Best Score" value={String(bestScore)}/><StatRow label="Level Reached" value={String(finalLevel)}/></View>{!continueUsed&&rewardedLoaded&&<Pressable style={styles.continueButton} onPress={handleContinue}><Text style={styles.continueButtonText}>▶ Watch Ad to Continue</Text></Pressable>}<Pressable style={styles.playAgainButton} onPress={handlePlayAgain}><Text style={styles.playAgainText}>PLAY AGAIN</Text></Pressable><Pressable onPress={()=>navigation.replace('Home')} hitSlop={12}><Text style={styles.homeLink}>Back to Home</Text></Pressable></View></SafeAreaView>}
function StatRow({label,value,highlight}){return <View style={styles.statRow}><Text style={styles.statLabel}>{label}</Text><Text style={[styles.statValue,highlight&&styles.statValueHighlight]}>{value}</Text></View>}
const styles=StyleSheet.create({flex:{flex:1,backgroundColor:colors.background},content:{flex:1,alignItems:'center',justifyContent:'center',paddingHorizontal:32},reason:{color:colors.danger,fontSize:14,fontWeight:'700',marginBottom:4},title:{color:colors.textPrimary,fontSize:30,fontWeight:'800',marginBottom:12},newRecord:{color:colors.warning,fontSize:15,fontWeight:'700',marginBottom:16},statsBlock:{width:'100%',backgroundColor:colors.surface,borderRadius:18,paddingVertical:8,paddingHorizontal:20,marginBottom:28},statRow:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.buttonIdle},statLabel:{color:colors.textSecondary,fontSize:15},statValue:{color:colors.textPrimary,fontSize:15,fontWeight:'700'},statValueHighlight:{color:colors.warning},continueButton:{backgroundColor:colors.accent,paddingVertical:14,paddingHorizontal:32,borderRadius:28,minWidth:240,alignItems:'center',marginBottom:14},continueButtonText:{color:colors.background,fontSize:15,fontWeight:'800'},playAgainButton:{backgroundColor:colors.primary,paddingVertical:16,paddingHorizontal:48,borderRadius:32,minWidth:240,alignItems:'center',marginBottom:16},playAgainText:{color:colors.textPrimary,fontSize:17,fontWeight:'800',letterSpacing:1},homeLink:{color:colors.textSecondary,fontSize:14,fontWeight:'600'}});
